name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code on this fresh ubuntu OS
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: Docker_Database
        password: 12345

    - name: Set up a unique tag for our docker image
      id: tag
      run: echo "tag=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag Docker_Database/simple-docker-hub:${{ env.tag }}

    - name: Push the Docker image to our DockerHub repo Simple Docker Hub
      run: docker push Docker_Database/simple-docker-hub:${{ env.tag }}
